/**
 * Define o layout base para todas as páginas da aplicação Next.js.
 */

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

/**
 * Componente RootLayout:
 * - Renderiza o conteúdo das páginas dentro de um elemento `<html>` e `<body>`.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
